!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - clip_range
    - 0.2
  - - ent_coef
    - 0.0
  - - env_wrapper
    - minigrid.wrappers.FlatObsWrapper
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 0.00025
  - - n_envs
    - 8
  - - n_epochs
    - 10
  - - n_steps
    - 128
  - - n_timesteps
    - 5000000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
