!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 32
  - - ent_coef
    - 0.001
  - - gae_lambda
    - 0.99
  - - gamma
    - 0.999
  - - n_envs
    - 16
  - - n_epochs
    - 4
  - - n_steps
    - 256
  - - n_timesteps
    - 500000.0
  - - policy
    - MlpPolicy
